spring.application.name=board_2

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3306/board_2?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
